apiVersion: v1
kind: Service
metadata:
  name: ccdcca2-service
  labels:
    app: ccdcca2
spec:
  selector:
    app: ccdcca2
  ports:
    - protocol: TCP
      port: 3000 # Service port
      targetPort: 3000 # Container port
  type: NodePort # change to LoadBalancer if running in cloud